commandline/WSL/faq.md
Added some clarification to code snippets and did some minor reformatting.
=> Code snippet cleanup

commandline/WSL/about.md
easy to miss the install TOC, expected a install instructions here.
=> add link to install

commandline/WSL/faq.md
=> updated faq.md

commandline/WSL/install_guide.md
These docs are great!! Just tweaking working (restart instead of reboot).
=> Minor terminology change

commandline/WSL/about.md
Minor changes to 'Get started' list for better readability.
=> Changed 'Get started' list

commandline/WSL/faq.md
Explains how to create a symbolic link to use a Windows file from an Linux app.
=> Add How do I use a Windows file with a Linux app?

commandline/WSL/about.md
At least I think it is a typo.
=> Fix a typo in WSL/about.md

commandline/WSL/install_guide.md
=> really minor spellcheck

commandline/WSL/interop.md
needs the minor space inserted
=> header tweaks

commandline/WSL/reference.md
=> header change #2

commandline/WSL/install-on-server.md
In my previous PR I've added a character (by mistake) at the beginning of the article. That character ruined the header.
=> Fix a header

commandline/WSL/user_support.md
Updated users and permissions page to reflect multi-distro.  lxrun commands removed/minimized.  distro specific instructions.
=> Updated users and permissions page to reflect multi-distro

commandline/WSL/user_support.md
When you have a dodgy wireless keyboard that occasionally drops keystrokes, sometimes you don't actually know your password. That's the excuse I use anyway.
Here's the steps to finish out the process on creator's update
=> Add missing steps to recover a password

commandline/WSL/about.md, commandline/WSL/faq.md, commandline/WSL/install-on-server.md, commandline/WSL/install-win10.md, commandline/WSL/interop.md, commandline/WSL/reference.md, commandline/WSL/release-notes.md, commandline/WSL/troubleshooting.md, commandline/WSL/user-support.md, commandline/WSL/wsl-config.md, commandline/index.md
Preparing for the move to docs.microsoft.com
=> Updated docs with SEO changes

commandline/WSL/install-win10.md
Move what looks like three sections to two with the second having two options based on your windows version.
=> Update install-win10.md sections

WSL/troubleshooting.md
Hey there! 👋 
I think these typos should be corrected so that they don't confuse other users. 😄
=> fixed typos!

WSL/interop.md, WSL/reference.md
Added WSLENV and tested/updated all bash -c references to WSL.exe.
=> Updated interop doc to FCU

WSL/wsl-config.md
The command was `wsl /list` when it should be `wslconfig /list`.
=> Fixed a typo in wsl-config.md

WSL/about.md
https://blogs.msdn.microsoft.com/commandline/learn-about-bash-on-windows-subsystem-for-linux/ results in page not found
=> Remove dead link

WSL/install-win10.md
And simplified sentence and fixes #158
=> Fix windows store to microsoft, UNIX to LINUX

WSL/docfx.json
You can access the previous Livefyre comments at: https://aka.ms/skyeye/livefyre
=> Implement new docs feedback system

WSL/TOC.md, WSL/build-custom-distro.md
Creating a new doc and TOC item. Distro launcher documentation that went live today
=> Adding doc for custom distro creation

WSL/release-notes.md
Release notes for 17128 & 17133 fast
=> Release notes for 17128 & 17133 fast

WSL/release-notes.md
Relese notes for 17639 skip ahead build
=> Relese notes for 17639 skip ahead build

WSL/release-notes.md
=> 17639 release note updates

WSL/install-on-server.md
Fixed in response to https://github.com/MicrosoftDocs/WSL/issues/182
=> Updated for Server 2019

WSL/faq.md
Changed "we only support x64 CPUs"
=> ARM CPUs now supported since BUILD 2018

WSL/about.md
Changing tags with team blogs to reflect the current go-to place for updated info
=> Updating team blog resources

WSL/faq.md
Fairly commonly asked question on the web so would be great to add to the FAQ
=> Provide instructions on port passthrough

WSL/initialize-distro.md
=> Fixed link to WSL Docs

WSL/install-win10.md
Adds a missing `s` in the page title.
=> Fix typo in WSL page title

WSL/faq.md
Fixes https://github.com/Microsoft/WSL/issues/1740.
=> Several FAQ improvements

WSL/TOC.md
Add a link to initialize-distro.md to TOC
=> Add an entry for "Initialize Distro" topic to TOC

WSL/TOC.md
Added the new doc page to the TOC
=> Updated the TOC to include enterprise.md

WSL/about.md
=> Add localization priority

WSL/troubleshooting.md
remove redundant Powershell from code snippet in *Confirm WSL is enabled* section
=> Remove redundant "Powershell" from code snippet

WSL/install-manual.md
An aka.ms link will need to be created for Fedora Remix for WSL.
=> Clarify OpenSUSE/SUSE Versions, Add Fedora Remix for WSL

WSL/install-win10.md
Update with a very common error resolution ( users install WSL directly from windows store and ignore the activation process from control panel or powershell
=> Update for new error resolution

WSL/wsl-config.md
Hi,
Previously, "ie" was misspelled, and anyway I think "for example" fits here better.
=> Clarify bullet point

WSL/install-legacy.md
Change `accpted` to `accepted`
=> Fix typo in install-legacy.md

WSL/build-custom-distro.md
Change `Distro Launcher Gitub repo` to `Distro Launcher GitHub repo`
=> Fix typo in build-custom-distro.md

WSL/troubleshooting.md
Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
=> Fix log message rendering

WSL/wsl2-ux-changes.md
Added powershell command to find the VHD location and the missing 'diskpart' command.
=> added command to find vhd location

WSL/wsl2-ux-changes.md
Fixes https://github.com/MicrosoftDocs/WSL/issues/426
=> Defines VHD the first time it's mentioned.

WSL/troubleshooting.md
=> “Susbystem” > “Subsystem”

WSL/faq.md
Per Loc Bug https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1596677. 
Remove duplicate URL target and update URL to redirected target. (GUI instructions for enabling the WSL don't seem to exist anymore on Docs.)
=> LocBug: Update faq.md

WSL/wsl2-ux-changes.md
- Made newer builds more prominent as 20H1 release is soon
=> Moved instructions for WSL access in Windows

WSL/file-permissions.md, WSL/release-notes.md, WSL/user-support-archived.md, WSL/user-support.md, WSL/wsl2-about.md, WSL/wsl2-install.md, WSL/wsl2-ux-changes.md
Adding changes from staging docs
=> Docs staging

WSL/troubleshooting.md
https://github.com/Microsoft/WSL/issues/3181
=> Add permission error section to FAQ

WSL/wsl-config.md
Added info about .wslconfig to wsl-config.md
=> Added .wslconfig changes to wsl-config.md

WSL/wsl2-kernel.md
Installation steps are not codes.
=> Remove code block style syntax

wsl-samples/afunix-wsl-interop/windows_server/af_unix_win_server.cpp
- Address C4996 and C4477
- Address https://github.com/MicrosoftDocs/WSL/issues/622
=> Fix warnings in sample interop code

WSL/faq.md
I had looked to this page previously for info on how to move distros among drives, but I had not noticed that the answer was implied in the discussion of backing up. So I am proposing here a slight refinement to the question and the answer, to make those points stand out better. This is important for those who may come looking for info when their drive is filling and WSL (the distros and/or their apps) are a culprit.
=> refine FAQ about backup to cover move of distros also

WSL/install-win10-archive.md
Translator has reported possible source content issue. 
Affected Line: 34
Description: duplicated square bracket removed
=> M50115 - Fixing Typo

WSL/install-win10.md, WSL/toc.yml, WSL/tutorials/gpu-compute.md
Links to DirectML install / setup tutorials - wait until those are live to publish.
=> Add GPU acceleration page

WSL/install-win10.md
Why make it harder than necessary to get the MSI-package?
=> Added a clickable link to the MSI kernel update

WSL/file-permissions.md, WSL/kernel-release-notes.md
=> Fix link to 4.19.121 release tag on Github

WSL/install-win10-archive.md, WSL/install-win10.md, WSL/toc.yml, WSL/tutorials/wsl-database.md
...and set-default note regarding os version needed
=> Push live get started with databases tutorial

WSL/faq.md
Based on this issue: https://github.com/MicrosoftDocs/WSL/issues/784
=> Add workflow example

WSL/about.md, WSL/compare-versions.md
..based on dev env user study feedback wanting a short video to explain what wsl is
=> embed what can i do with wsl video

WSL/troubleshooting.md
=> Add troubleshooting for Error: 0x1bc

WSL/about.md, WSL/compare-versions.md, WSL/faq.md, WSL/install-on-server.md, WSL/install-win10.md, WSL/reference.md, WSL/release-notes.md, WSL/wsl2-about.md, WSL/wsl2-faq.md, WSL/wsl2-index.md
Edited descriptions for length (100-160 characters) for SEO.
User Story [1610813](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1610813)
=> Edited descriptions for length US1610813.

WSL/tutorials/wsl-git.md
=> Fix minor typo

WSL/tutorials/wsl-containers.md
=> Fix a typo

WSL/release-notes.md
=> add code quotes around wsl --mount

.openpublishing.redirection.json, WSL/wsl2-kernel.md
Added wsl2-kernel.md back in and removed the redirection.
=> Fix kernel install MSI not showing up for some users

WSL/about.md, WSL/enterprise.md, WSL/faq.md, WSL/file-permissions.md, WSL/index.md, WSL/initialize-distro.md, WSL/install-manual.md, WSL/install-win10.md, WSL/interop.md, WSL/release-notes.md, WSL/troubleshooting.md, WSL/tutorials/gpu-compute.md, WSL/tutorials/wsl-containers.md, WSL/tutorials/wsl-database.md, WSL/tutorials/wsl-vscode.md, WSL/user-support-archived.md, WSL/wsl-config.md, WSL/wsl2-mount-disk.md
- Updating full URL links that point to docs.microsoft.com to a Site Relative or Relative link.
- Updating Site Relative links that point inside this Docset to a Relative link.
- Updating MSDN/TechNet/ACOM links that point to docs.microsoft.com to a Site Relative or Relative link.
- Updating short (AKA.ms/FWLinks) links that point to docs.microsoft.com to a Site Relative or Relative link.
cc @mattwojo and @craigloewen-msft
=> Links: WSL - Pass 1

WSL/troubleshooting.md
Updating section describing what to do when virtualization not enabled to include error message and error code.
=> Update virtualization not enabled error section

WSL/wsl2-mount-disk.md
=> Capitalize “Linux” in doc title

WSL/compare-versions.md, WSL/troubleshooting.md
Follow up on #880.
Referencing @craigloewen-msft [comment](https://github.com/MicrosoftDocs/WSL/pull/880#issuecomment-700145356) considering all requested changes. Double checked for typos and wording, should be safe to merge.
New PR made as I accidentally deleted the fork branch for #880.
For further details please see #880 and original issue #878.
=> Issue: Windows commands not accessible inside distribution terminal

WSL/install-win10.md
Added general instructions letting Insiders know about the latest install experience.
=> Add wsl --install instructions to win10-install.md

WSL/wsl2-kernel.md
@mattwojo Monthly LinkRepair for this repo.
=> Links: WSL (2020-11)

WSL/install-win10.md
Corrected note about conversion-time of WSL-upgrade, which was placed in the wrong section.
Solves #1042
=> WSL-installation doc: corrected position of note

WSL/wsl2-mount-disk.md
=> Links: WSL (2021-01)

WSL/compare-versions.md, WSL/install-win10.md
@mattwojo 
**Summary:** Updating Meta tags characters under 150.
URL | Current Meta   TAG | Characters | SEO Meta Tag | Characters (under 150 Recommended)
-- | -- | -- | -- | --
https://docs.microsoft.com/en-us/windows/wsl/compare-versions | Compare   version 1 and version 2 of the Windows Subsystem for Linux. Learn whats new   in WSL 2 - actual Linux kernel, faster speed, full system call compatibility.   WSL 1 works better if your storing files across operating file systems. You   can expand the size of your WSL 2 Virtual Hardware Disk (VHD). | 300 | **Compare   version 1 and version 2 of the Windows Subsystem for Linux. Learn whats new  in WSL 2** . | **94**
https://docs.microsoft.com/en-us/windows/wsl/install-win10 | Learn   how to install Linux distributions on your Windows 10 …
=> SEO: Update_meta_tags

WSL/enterprise.md, WSL/install-win10.md
Monthly links cleanup.
/cc @mattwojo
=> Links: WSL (2021-02)

WSL/release-notes.md
=> fix bad URL

WSL/install-legacy.md, WSL/install-on-server.md
Monthly links cleanup.
/cc @mattwojo
=> Links: WSL (2021-03)

WSL/about.md, WSL/compare-versions.md, WSL/enterprise.md, WSL/faq.md, WSL/file-permissions.md, WSL/index.md, WSL/install-legacy.md, WSL/install-on-server.md, WSL/install-win10.md, WSL/kernel-release-notes.md, WSL/reference.md, WSL/release-notes.md, WSL/troubleshooting.md, WSL/tutorials/gpu-compute.md, WSL/tutorials/wsl-containers.md, WSL/tutorials/wsl-database.md, WSL/tutorials/wsl-git.md, WSL/tutorials/wsl-vscode.md, WSL/user-support.md, WSL/wsl2-faq.md, WSL/wsl2-mount-disk.md
@mattwojo 
URL | Current Page   Title | Characters | SEO Page Title | Characters (under 60 Recommended)
-- | -- | -- | -- | --
https://docs.microsoft.com/en-us/windows/wsl/ | An overview on   the Windows Subsystem for Linux \| Microsoft Docs | 63 | Windows   Subsystem for Linux Documentation \| Microsoft Docs | 58
https://docs.microsoft.com/en-us/windows/wsl/about | About Windows   Subsystem for Linux \| Microsoft Docs | 50 | What   is Windows Subsystem for Linux \| Microsoft Docs | 52
https://docs.microsoft.com/en-us/windows/wsl/compare-versions | Comparing WSL   2 and WSL 1 \| Microsoft Docs | 42 | Comparing WSL   1 and WSL 2 \| Microsoft Docs | 42
https://docs.microsoft.com/en-us/windows/wsl/install-win10 | Install   Windows Subsystem for Linux (WSL) on Windows 10 \| Microsoft Docs | …
=> SEO: Update page_titles

WSL/troubleshooting.md
corrected "THe" to "The" in documentation
=> correction in spelling

WSL/reference.md
Credits - https://superuser.com/questions/1501478/wsl-is-not-recognized-as-an-internal-or-external-command?newreg=4e6e49a0b159442782e0c3fae97c0e82
=> added corrected wsl path for 32-bit process usage

WSL/tutorials/wsl-database.md
=> Fix typo `inid.d` -> `init.d`

WSL/kernel-release-notes.md
=> Fix typo in WSL kernel release notes

WSL/install-win10.md
Line 33: - Open a command line windows with Administrator privileges
to:         - Open a command line window with Administrator privileges
=> fixed a typo

WSL/wsl-config.md
- Added In Preview Options section at Line 354
- Added option  **guiApplications** to turn on/off support for WSL GUI applications
**Note:** Other In Preview Options may be added if present.
=> fix: Added In Preview Options for .wslconfig

WSL/troubleshooting.md
Add additional troubleshooting information for Microsoft Defender Firewall users on Windows 10.
=> Update no Internet access in WSL

WSL/tutorials/gui-apps.md
=> Update Intel GPU driver for WSL

WSL/wsl-config.md
To be clear, I am offering this edit via the github web ui. I only changed one line, here line 81. Somehow the UI is indicating also a change of line 231, but I did not change it (and I see the two lines to be identical, in any case).
=> correct mistaken filename reference

WSL/troubleshooting.md
path not complete so added % on line 46
=> added % on line 46

WSL/store-release-notes.md
Updated the store release notes to point to Github.
=> Updated store-release-notes.md to point to Github

.gitignore, WSL/connect-usb.md, WSL/install.md, WSL/toc.yml
* Add connect usb doc, update windows install prereq
* Add usb to toc
* Add video link
* Update WSL/connect-usb.md
Co-authored-by: Craig Loewen <crloewen@microsoft.com>
* Update WSL/connect-usb.md
Co-authored-by: Craig Loewen <crloewen@microsoft.com>
* Update WSL/connect-usb.md
Co-authored-by: Craig Loewen <crloewen@microsoft.com>
* WSL 2 requirement
* Add Windows 10 note
Co-authored-by: Craig Loewen <crloewen@microsoft.com>
=> Add Connect to USB doc (#1355)

WSL/case-sensitivity.md
- Case-insenstive -> Case-insensitive
- FOO.text -> FOO.txt
=> fix Case-insensitive description

WSL/install-manual.md
> Using Windows Terminal enables you to open multiple tabs or window panes to display and quickly switch between multiple Linux distributions or other command lines (PowerShell, Command Prompt, ~~PowerShell~~, Azure CLI, etc).
=> Removed duplicate of `PowerShell`

WSL/compare-versions.md
Line 47: 
- [Set your Linux distribution version to WSL 1 to WSL 2](./basic-commands.md#set-wsl-version-to-1-or-2) 
changed to
- [Set your Linux distribution version from WSL 1 to WSL 2](./basic-commands.md#set-wsl-version-to-1-or-2)
=> Change 'to' to 'from'

WSL/basic-commands.md
=> typo (basic-commands): `--quite` -> `--quiet`

WSL/troubleshooting.md
This change adds instructions to diagnose and fix situations where hypervisorlaunchtype is off in the boot configuration.
=> Add troubleshooting instructions for disabled hypervisor launch

WSL/tutorials/gpu-compute.md
Adding in references to Windows 11 and Windows 10 where this functionality is supported. Along with updating the wording and link to the Windows AI docs.
=> Update GPU compute WSL docs

WSL/install.md
Hi!
Before:
> ... by selecting **Start** > **Settings** > **Windows Update **> **[Check for updates](ms-settings:windowsupdate)**.
After:
> ... by selecting **Start** > **Settings** > **Windows Update** > **[Check for updates](ms-settings:windowsupdate)**.
=> WSL/install.md: minor fix: markdown bold format

WSL/tutorials/gpu-compute.md
https://docs.microsoft.com/en-us/windows/wsl/tutorials/gpu-compute
https://github.com/MicrosoftDocs/wsl/blob/main/WSL/tutorials/gpu-compute.md
#PingMSFTDocs
=> Typo "Tensorflow"→"TensorFlow"

WSL/install.md
Looks like many people need this to be clarified. Even though a better message appear in the latest WSL version from store, it won't arrive soon to Windows 10 users
=> Add a note in case that WSL is already installed #1422 #1410 #1408 #1054

WSL/use-custom-distro.md
This redirect is actually not present in the commands block to which this note is related.
=> WSL/use-custom-distro.md: Remove redirect from wheel command note.

WSL/faq.yml
Set ms.topic: faq where YamlMime:FAQ
Note the following:
- DocuTune drives improved quality of technical content by finding and automatically correcting a broad set of issues in Markdown and YAML files. DocuTune performs these updates intelligently, only making corrections in the sections of a document where the correction is suitable.
- DocuTune PRs often standardize spacing, formatting, and casing of Markdown elements to support the DocuTune onboarding process.
- DocuTune PRs might contain other minor edits noticed during a manual review.
- DocuTune PRs might include files whose Acrolinx score was below the target threshold prior to this PR.
- Delimiters such as asterisks and backticks may be added to link descriptions or alt-text to denote UI elements or other string literals that …
=> Set ms.topic: faq where YamlMime:FAQ

WSL/filesystems.md
Fixed the typo for issue https://github.com/MicrosoftDocs/WSL/issues/1468
=> Fixed 'case-insenstive' typo in filesystems.md

WSL/install-on-server.md
Addresses https://github.com/MicrosoftDocs/WSL/issues/1451
=> Change to appx from exe launcher

WSL/tutorials/wsl-database.md
Resolves https://github.com/MicrosoftDocs/WSL/issues/972
=> Update for empty SQLite database error

WSL/basic-commands.md
Addresses https://github.com/MicrosoftDocs/WSL/issues/1164
=> Add warning re def user update on import distro

WSL/case-sensitivity.md
wsl.config doesn't exist and is meant to be wsl.conf  here
Signed-off-by: June <june@eridan.me>
=> Correct wsl.config to wsl.conf

WSL/enterprise.md
**Global effort to fix broken links**
The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!
=> [BrokenLinksH2] fixing broken link

WSL/case-sensitivity.md
Change "from it's parent directory" to "from its parent directory".
=> Spelling correction

WSL/tutorials/gpu-compute.md
Added additional guidance to make it easier to get WSL setup with NVIDIA CUDA, TensorFlow-DirectML, and PyTorch-DirectML.
=> Update setup for WSL with CUDA or DirectML

WSL/wsl-config.md
https://dev.azure.com/ceapex/Engineering/_workitems/edit/617890
=> Enable experimentation

WSL/install.md
Small wording fix on install page.
=> Updated install.md

WSL/wsl-config.md
* Update boot command
* Update wsl-config.md
=> Update boot command (#1572)

WSL/kernel-release-notes.md
Updating the kernel-release-notes.md by adding the latest versions in the documentation.
=> Updating the kernel-release-notes.md

WSL/tutorials/linux.md
Changed some text in the 'Working with files and directories' section.
- still need to add alt-text for the GIFs
- still need to tweak the 'Using Pipes and Redirect Operators' section so it's clear what is the shell command and what is the output of the command. I'm also thinking adding some GIFs here would be cool :)
=> Added images and changed some text

WSL/faq.yml, WSL/tutorials/wsl-containers.md
**Global effort for the Microsoft Learn platform rebrand**
The Microsoft team is applying changes to content for the Microsoft Learn platform rebrand. Changes include modifications to current Microsoft Learn and Microsoft Docs terminology as well as associated domain name and content URL path changes.
Please review this draft PR and provide any necessary comments as soon as possible. Because these fixes are tightly scoped, we have approval to automatically merge these changes to the default branch for publication.
This PR was generated via DocuTune. It includes only targeted fixes and minor formatting adjustments.
CorrelationId: d8c4c3ac-d49a-4c95-9ddc-9822ca297907
InitiativeId: docutune-rebranding-2022-09
PointOfContact: Alex Buck
=> [BULK UPDATE] DocuTune - Rebranding

WSL/tutorials/wsl-database.md
Update the 2019 survey to a newer(2021) one.
=> Update survey to a newer one.

WSL/troubleshooting.md
Replaced the word 'man' with "may" in line 481
=> Fixed typo

WSL/install.md
=> Update install text (#1646)

WSL/basic-commands.md, WSL/install.md
Updated the commands to include the latest for the Microsoft Store version of WSL
=> Store commands update

WSL/docfx.json
*High priority PR for navigation and breadcrumb compliance* 
This PR addresses required fixes to get content to basic compliance with site findability standards by 12/30/22. The progress of this effort is actively being reported to Scott Guthrie and his SLT in support of content quality initiatives.
---
A Pull Request has been made from the Learn Platform’s Metadata Management System. Please review and merge this Pull Request within 5 days. If you have any questions or concerns about the purpose of these metadata updates, please contact docsmetarequests@microsoft.com. If you are not the correct contact for this content and repository, please notify Learn-Metadata-Admin@microsoft.com. 
If this Pull Request is not merged within 14 days, it will be automatically merged by our system to …
=> [METADATA UPDATE] Global metadata/header/navigation changes 

WSL/wsl-config.md
Please add **hacktoberfest-accepted** to the PR if you accept it.
=> Add documentation about safeMode

WSL/wsl2-mount-disk.md
The Windows Store version of WSL supports --mount, even on Windows 10.
=> Info about support for --mount in Store version

WSL/networking.md
`netsh` is not a PowerShell command, it is Windows command
=> Correct description of example command

WSL/tutorials/gui-apps.md
- Fixes https://github.com/MicrosoftDocs/WSL/issues/1684 .
- Also fixes https://github.com/microsoft/wslg/issues/429.
- Also fixes https://github.com/microsoft/wslg/issues/776.
- Update link to GPU driver from Linux GUI documentation.
=> Update link to GPU driver from Linux GUI documentation

WSL/troubleshooting.md
https://learn.microsoft.com/en-us/windows/wsl/troubleshooting 
https://github.com/MicrosoftDocs/wsl/blob/main/WSL/troubleshooting.md 
#PingMSFTDocs
=> Typo "Github"→"GitHub"

WSL/install-on-server.md
Presumably fixes this 
On https://learn.microsoft.com/en-us/windows/wsl/install-on-server#install-wsl-on-previous-versions-of-windows-server
=> Fix weird codeblock in Server

WSL/tutorials/gui-apps.md
duplicate mention of PowerShell, remove completely or maybe mention Bash
=> duplicate mention of PowerShell

WSL/tutorials/wsl-git.md
=> Update wsl-git docs

WSL/wsl2-mount-disk.md
Resolves the documentation typo as descirbed in  #1827
=> Fixed typo in docs

WSL/tutorials/wsl-database.md
=> docs: write out flag in `WSL/tutorials/wsl-database.md`

WSL/enterprise.md, WSL/intune.md, WSL/networking.md, WSL/toc.yml, WSL/wsl-plugins.md
Added WSL plugin docs, Intune docs, and reconfigured networking and enterprise docs to have WSL Enterprise info.
=> Added WSL enterprise feature info

WSL/compare-versions.md, WSL/disk-space.md, WSL/enterprise.md, WSL/intune.md, WSL/networking.md, WSL/troubleshooting.md, WSL/tutorials/wsl-containers.md, WSL/wsl-config.md
* Reorganize, reword config doc
* fix hostname command
* Clarify to resolve https://github.com/MicrosoftDocs/WSL/issues/1722
* Add systemd and ipv6 to comparison table
* Update prereqs for docker
* Fix based on issue 1793
* Add more context to address issue 1795
* Resolve issue 1798
* Add note about hostname flag IP differences
* Add note about terminate command
* Fix hardcoded links
* Fix links
* Editorial fixes
* Remove repeated anchor links
* Fix firewall config link
=> Resolve issues Nov 23

WSL/install.md
Added missing "-" in the set default command.
=> Fixes typo in set default command

WSL/wsl-config.md
Fix incorrect default _firewall_ setting in experimental features.
=> Edited default setting of hyper-v firewall

WSL/faq.yml
Fixed a few small formatting and writing errors. (ie -> i.e., missing periods at the end of sentences)
=> Fixing small formatting and writing errors.

WSL/networking.md
The code block is not closed properly; therefore, the code is not highlighted as such
=> Fix broken code block and bookmark link

WSL/enterprise.md, WSL/install.md
Fix punctuation and typo errors. https://github.com/MicrosoftDocs/WSL/issues/1673
=> Fix punctuation errors

WSL/troubleshooting.md
Some small formatting improvements.
Also added the command to restart the hns service.
=> small improvements in troubleshooting.md

WSL/basic-commands.md, WSL/faq.yml
'changes to locale to' -> 'changes the locale to'
=> Update faq.yml -- tiny grammar change

WSL/networking.md
Fix bad apostrophe under networking section
=> Fix bad apstrophe under mirrored mode networking section

WSL/tutorials/wsl-git.md
Fixes https://github.com/MicrosoftDocs/WSL/issues/1651
=> Fix to point to the correct section of troubleshooting page

WSL/compare-versions.md
Fixes https://github.com/MicrosoftDocs/WSL/issues/1907
=> Correct marking of IPv6 support for WSL1

WSL/use-custom-distro.md
Current one will get error "/usr/bin/ls: /usr/bin/ls: cannot execute binary file"
=> Fix docker run command

WSL/install-manual.md
=> Update install-manual.md to include Ubuntu 24.04

WSL/wsl-config.md
Remove experimental useWindowsDnsCache config
=> Remove experimental useWindowsDnsCache config

WSL/docfx.json
change author from craig to matt
add craig as ms.reviewer
=> Update author metadata

WSL/build-custom-distro.md
Fix oobe delete user path
Rename best practices to recommendations
Minor writing style updates
=> Final editorial review update

WSL/tutorials/gpu-compute.md
Resolves https://github.com/MicrosoftDocs/WSL/issues/2044
=> Fix pytorch directml install command

ThirdPartyNotices
See https://ceapex.visualstudio.com/Engineering/_workitems/edit/997743.
=> Update links and text in ThirdPartyNotices per CELA request

.github/ISSUE_TEMPLATE/doc-issue.yml, WSL/build-custom-distro.md, WSL/compare-versions.md, WSL/disk-space.md, WSL/docfx.json, WSL/networking.md, WSL/systemd.md, WSL/troubleshooting.md, WSL/tutorials/wsl-database.md, WSL/wsl-config.md
=> Main > Live (#2122)

WSL/about.md, WSL/build-custom-distro.md, WSL/case-sensitivity.md, WSL/compare-versions.md, WSL/connect-usb.md, WSL/disk-space.md, WSL/filesystems.md, WSL/install-on-server.md, WSL/install.md, WSL/kernel-release-notes.md, WSL/networking.md, WSL/release-notes.md, WSL/setup/environment.md, WSL/store-release-notes.md, WSL/systemd.md, WSL/troubleshooting.md, WSL/tutorials/gpu-compute.md, WSL/tutorials/gui-apps.md, WSL/tutorials/linux.md, WSL/tutorials/wsl-containers.md, WSL/tutorials/wsl-database.md, WSL/tutorials/wsl-git.md, WSL/tutorials/wsl-vscode.md, WSL/use-custom-distro.md, WSL/wsl2-mount-disk.md
https://dev.azure.com/msft-skilling/Content/_workitems/edit/429984
=> Bulk update ms.topic

WSL/faq.yml
Added a question and answer to the FAQ.
=> Updated FAQ

WSL/wsl-config.md
=> Updated wsl_config.md
