commandline/WSL/install_guide.md

This patch removes repeated prerequisites. Also are non-insider users with anniversary update able to use Bash on Windows? I remove it in this patch, but I can add it back if joining insider program is still required.

[install guide.md] Is joining insider program required for using WSL?

---

commandline/WSL/about.md

The phrase "delivered by an" should not be there under the first bullet point under what "Bash/WSL allows" you to do.

Removed the incomplete words from the first bullet point

---

commandline/WSL/faq.md

According to the release note, the PING command no longer requires admin privileges since Build 14926.

Update FAQ: PING no longer needs admin privilege

---

commandline/WSL/faq.md

Trying to run apt-get will fail without using sudo (or running as root).

apt-get commands require using sudo

---

commandline/WSL/about.md

WSL's about page had a title and description that said "Linux Subsystem for Windows".  This PR updates it to be consistent with "Windows Subsystem for Linux"

Updated Windows Subsystem for Linux Page's Title and Description from LSW to WSL

---

commandline/WSL/faq.md

Also used **\`\`\`bash** instead of **\`\`\` BASH**, and  **\`\`\`batchfile** instead of **\`\`\` CMD**.
(Lowercase and no space is traditional here, and there's no [language entry](https://github.com/github/linguist/blob/7be6fb013864b59e7c9ba76e3c0062dd95cedc76/lib/linguist/languages.yml#L376) for "cmd".)

Bash, not BASH

---

WSL/wsl-config.md

Please do not use U+201C/U+201D as U+0022.
It will not work with non-English system locale.

Replace U+201C/U+201D to U+0022

---

WSL/troubleshooting.md

Host keys are missing under /etc/ssh
it had to purge&install openssh-server to have keys generated and available
Seems like its a bug. I suggest to further investigate it.

openssh-server host keys are missing /etc/ssh

---

WSL/about.md

Windows Subsystem for Linux (WSL) let you run GNU\Linux free software using a preferred distribution.
GNU is not a trade mark, nor patented. You can use it freely describing the free software tools you can now run under Windows also.

Language improvement on "tools"

---

WSL/install-manual.md

Replace "Windows Store" with "Microsoft Store".
Replace "command-line" with "command line" when it's used as a noun and not as an adjective.

Replace Windows Store with Microsoft Store

---

WSL/build-custom-distro.md

The doc refers to a blog post but doesn't link to it.  This adds the link.

Add missing link to build-custom-distro.md

---

WSL/about.md

Fix broken link to install guide and directed it to the guide to installing on Windows 10. (Improve capitalization of the section that the broken link was in.)
Thanks!
Happy Hacktoberfest!

Fix broken link to install guide

---

WSL/user-support.md

This makes the start of the warning about elevated processes a easier to read. When first reading through the page, I was tripped up with some odd syntax (particularly "that").
The whole warning now has quite a few slashes, but I think it works.
Not sure which branch to submit PR against, but it looks like "live" is the default - if needed, we can change.

Make elevated permissions warning flow better

---

WSL/install-manual.md

The instructions now fully explain how to install via PowerShell and then links user to initializing step.
See issue #265

Fixed cyclical instructions for installation via PowerShell

---

WSL/wsl2-ux-changes.md

> The picture below shows an example of this by connecting to a python server running in Windows via curl. 
The picture following this sentence shows a Node.js script being executed on Windows and a curl request being sent to it, but the line above says the server is in fact in Python.
Also, correcting nodeJS to Node.js in the following line -
> The picture below shows an example of this by connecting to a nodeJS server using the Edge browser.

Correcting python to Node.js

---

WSL/release-notes.md

there is a missing escape character for displaying the `\`.
The preview shows `Introduce %UserProfile%.wslconfig file for tweaking WSL2 settings` instead of `Introduce %UserProfile%\\.wslconfig file for tweaking WSL2 settings`
Therefore, if someone tries to copy the path in explorer, there will be an error

[Typo] Corrected `%UserProfile%\.wslconfig`

---

WSL/troubleshooting.md

Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.  
Description: invalid link is causing rendering problems on LOC pages

C117192: removing duplicated url inside link

---

WSL/troubleshooting.md

Signed-off-by: Kathryn Baldauf <kabaldau@microsoft.com>

update broken link to instructions for forcing diagnostic crash dumps on hangs

---

WSL/troubleshooting.md

Translator has reported possible source content issue. 
Description: Wrong source - 'conf' is correct

M43519: Fixing typo resolv.con/resolv.conf

---

WSL/wsl2-install.md

The previous commit changed several inline code markup into code blocks, and accidently left behind a backtick.

Remove extra backtick from previous commit

---

WSL/wsl2-install.md

WSL2 is now available for the 'Slow' ring as well but the documentation says you need to use the fast ring.

update instructions to include slow ring

---

WSL/troubleshooting.md

Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
Fixing Fenced code blocks alias according to StyleGuide: https://review.docs.microsoft.com/en-us/help/contribute/code-in-docs?branch=master#supported-languages

CC186442: Fixing Fenced code blocks alias

---

WSL/wsl2-kernel.md

The download link points to x64 but the text mentions it as AMD64. There is a separate note section below for AMD64

Issue #594: Incorrect Platform AMD64 instead of x64

---

.openpublishing.redirection.json

Here's what you need to know:
{
"redirections": [
{
"source_path": "wsl/subfolder/deprecated_file_name.md",
"redirect_url": "wsl/destination_file_name",
"redirect_document_id": true
},
1. source_path is the location of the file that we are getting rid of with a .md.
2. redirect_url is the location that you want that URL to redirect to... no .md. You can also use an entire URL (rather than a relative link) here if you prefer. For example: https://docs.microsoft.com/windows/wsl (be sure not to include the en-us language-location part of the url). 
3. redirect_document_id is true or false and determines whether the traffic data from the old page should be pulled to the new redirect page. For most new redirects this should be true... BUT you can only set this to true for a destination page …

Add redirect for initialize > install page

---

WSL/install-win10.md

I updated the install win10.md instructions. Specifically I added these changes:
* Changed the commands from PowerShell scripts to always use dism
* Adjusted the ordering and wording to (hopefully) more clearly instruct users to skip ahead if they only want WSL 1 and keep on reading for WSL 2
* Moved the 'set WSL 2 as your default' command up higher in the page.
* Removed some redundant links and notes to the manual install packages and notes about being on build 16215 or higher.
* Added a 'Further Resources' section at the bottom that goes over how to check your WSL version. We can expand this in the future to link to the getting started guides.
Let me know what you think!

Updated install win10.md instructions

---

WSL/install-win10.md

Ubuntu 20.04 LTS is released for a while, and I found that link to Ubuntu is missing in the Installation page, thus adding them.

Add link to Ubuntu and Ubuntu 20.04 LTS

---

README.md

Changes the redirect url of `Microsoft/Console` to `Microsoft/Terminal`

Fix redirect URL in README.md

---

WSL/tutorials/gpu-compute.md

Simplified the GPU compute section to emphasize the parallelization of math as the big win with a GPU. Removed some of the content in the install section as the high level workflows makes the most sense to call out IMO.

GPU compute and install section edits

---

WSL/about.md

These were missing spaces and weren't getting displayed correctly in the docs website.

Fix bullet point formatting on About page

---

WSL/install-win10.md

Single dash `wsl –set-version` is not going to work as syntax for this option must have double dash. The right one: `wsl --set-version`.
> --set-version \<Distro\> \<Version\>
Changes the version of the specified distribution.

wsl –set-version with single dash is faulty

---

WSL/build-custom-distro.md

The removed link ("Command-line UserVoice portal") leads to a 404 page that says: "This UserVoice instance is no longer available."

Removed dead link in the build-custom-distro.md file

---

WSL/compare-versions.md

Currently the steps in the [Accessing Windows networking apps from Linux (host IP)](https://docs.microsoft.com/en-us/windows/wsl/compare-versions#accessing-windows-networking-apps-from-linux-host-ip) paragraph of [Comparing WSL 2 and WSL 1](https://docs.microsoft.com/en-us/windows/wsl/compare-versions#understanding-wsl-2-uses-a-vhd-and-what-to-do-if-you-reach-its-max-size) page are rendered inline which makes it hard to read them:
The change makes them render on separate lines.

Make some steps more visible

---

WSL/wsl2-mount-disk.md

This change adds a mention that SD cards aren't supported by `wsl --mount`

Add SD cards to the list of wsl --mount limitations

---

WSL/faq.md

**Description:**
During a recent lookup in the FAQ based on a statement in a ticket in the MS ServerDocs pages, I noticed that 1 link points to an old and no longer maintained page (/previous-versions/) and some are permanently redirected from their previous site names (MSDN, TechNet) to their current pages.
This PR aims to improve the above noted issues as well as a couple of cosmetic details.
**Changes proposed:**
- [Remove-AppxPackage cmdlet] URL: 
(/previous-versions//hh856038(v=technet.10)) 
=> (https://docs.microsoft.com/powershell/module/appx/remove-appxpackage)
- [Do not change Linux files using Windows apps and tools] URL: 
(https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/) 
=> …

WSL/FAQ: update URLs to current docs

---

WSL/faq.md
WSL/troubleshooting.md

As stated on:
- https://github.com/microsoft/WSL/issues/4926#issuecomment-590829828
- https://github.com/microsoft/WSL/issues/5382#issuecomment-644703523

Add symantec to the list of firewalls which blocks WSL

---

WSL/install-win10.md

> To check your version and build number, select Windows logo key + R, type winver, select OK. (Or enter the ver command in Windows Command Prompt).
The `ver` command in Windows Command Prompt actually does not show necessary version number (Release ID).
```
> ver
Microsoft Windows [Version 10.0.19041.746]
```
To check Release ID in command line, you need the following command in PowerShell:
> PS > (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").ReleaseId
It's awkward and it's easier to use `winver`. I suggest to remove the description about `ver` command.

Remove description about ver command

---

WSL/install-win10.md

On non-English Windows versions, you might have to modify he search text, e.g. in German it would be `systeminfo | find "Systemtyp"`.

install-win10.md: add caveat concerning search expression

---

WSL/wsl-config.md

`case` option is available (Ref: https://devblogs.microsoft.com/commandline/per-directory-case-sensitivity-and-wsl/) for DrvFs but it is not documented in the mount options section here(https://docs.microsoft.com/en-us/windows/wsl/wsl-config#mount-options)

Add `case` in the mount option documentation

---

WSL/wsl2-mount-disk.md

Mounting disk or partitions belonging to a disk that is already in use is not an option and is the cause of several issues: #5997 #6015.
This patch updates the documentation to inform about the limitations of the command, preventing future users from discovering this too late.

Improve mount limitations documentation

---

WSL/install-win10.md

The following error can occur if the CPU is old enough to not support SLAT: 
"Error: 0x80370102 The virtual machine could not be started because a required feature is not installed."
The error message itself is not specific to the root issue and I think it would be helpful to list this possible cause here.
References:
https://github.com/microsoft/WSL/issues/4709
https://github.com/MicrosoftDocs/WSL/issues/846

add additional cause of error 0x80370102 - CPU does not support SLAT

---

WSL/troubleshooting.md

Enterprises tend to disable ICS (Internet Connection Sharing) as part of security hardening. This causes the underlying WSL 2 network, created by HNS, to fail since it relies on ICS.
This PR documents the ICS dependency.

Addition troubleshooting for enterprise scenarios

---

WSL/install-win10.md

Remove the link to Ubuntu 16.04 Windows Store item as it has been removed. I've left the direct link to the appx package as is still working, though I'm not sure I'd recommend 16.04 at this point as it will be EOL as of tomorrow. Can remove as part of this PR if people deem necessary.
Resolves issue #1172

Remove Ubuntu 16.04 as no longer available

---

WSL/compare-versions.md
WSL/faq.yml
WSL/wsl2-faq.yml

This PR is the result of running a Link Repair script on the included content. This script is primarily being run to cleanup links to function correctly in Air Gapped Clouds (AGC). Here's a breakdown of what the script that generated the changes in this PR fixes:
- docs.microsoft.com Fully Qualified Domain Name (FQDN) Links to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not
- azure.microsoft.com/documentation/articles that reflect to Docs to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not
- All known flavors of MSDN/TechNet domains (we know of 8 or 9 now) that reflect to Docs to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not
- This also includes cleanup of the appended query string for MSDN …

Links: WSL (2021-05)

---

WSL/troubleshooting.md

https://docs.microsoft.com/en-us/windows/wsl/troubleshooting
#PingMSFTDocs

Typo "Windows terminal"→"Windows Terminal"

---

WSL/tutorials/wsl-git.md

The old Git Credential Manager for Windows is deprecated, having been replaced by the cross-platform GCM Core.
I also fixed up a few points of confusion between "Git" and "GitHub", and fixed capitalization on "Git" where needed. ("Git" is the software project; "`git`" is the command-line binary.)

replace old GCM with GCM Core

---

WSL/troubleshooting.md

The link was missing a trailing hyphen.

Clarified ICS service hardening sentence and updated link.

---

WSL/wsl-config.md

Add the `nestedVirtualization` and `vmIdleTimeout` options from Insider builds [20175](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20175) and [20190](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20190) respectively

Update list of "In Preview Options" in .wslconfig

---

WSL/tutorials/wsl-database.md

We were creating `data/db` in `/home` but then tried to run the instance with path `~/data/db` which failed as
`home/accountname/data/db`  did not exist 
```
9. Make a directory to store data: `mkdir -p data/db`
10. Run a Mongo instance: `sudo mongod --dbpath ~/data/db`
```
This pr changes the command to run instance with home path.

Remove ~ path segment from command to run Mongo instance

---

WSL/tutorials/wsl-git.md

Per GCM Core docs, some additional configuration is needed in order to
authenticate with Azure Repos.
https://github.com/microsoft/Git-Credential-Manager-Core/blob/main/docs/configuration.md#credentialusehttppath

Document Git Configuration for Azure Repos

---

WSL/tutorials/wsl-vscode.md

The removed link ([Remote development with WSL tutorial](https://code.visualstudio.com/remote-tutorials/wsl/getting-started)) leads to a 404 page that says: "Sorry! It seems the page can't be found".

Fix dead link

---

WSL/toc.yml
WSL/wsl2-mount-disk.md

This change adds documentation for `wsl --mount --name` and `wsl --mount --vhd`, which are both available in WSL from the Microsoft store.
This change also removes the 'preview' mention on the WSL --mount page, because Windows 11 has been released.

Document wsl --mount --name and wsl --mount --vhd

---

WSL/tutorials/wsl-git.md

The Git Fundamentals team has changed the name of the Git Credential Manager Core tool to Git Credential Manager. The team has also migrated the repository into [its own org](https://github.com/GitCredentialManager). Updating the documentation in this repo to reflect these changes.

git credential manager: update name/links

---

WSL/store-release-notes.md

Closes issue  #1381 
It seems the full form of WSL was written wrongly as Windows Subsystem **from** Linux
when it should be  Windows Subsystem **for** Linux.
Very subtle but can be confusing for new documentation readers/ new WSL users.

fix: Typo in WSL full name. #1381 

---

WSL/faq.yml

The documentation FAQ says that serial/USB is not available, but just a few clicks away there's a semi-guide detailing how to get it up.
(github online edit added newline at end of file by itself 🤷‍♂️)

Link to `connect-usb.md` in FAQ about serial/usb

---

WSL/about.md
WSL/basic-commands.md
WSL/case-sensitivity.md
WSL/compare-versions.md
WSL/connect-usb.md
WSL/file-permissions.md
WSL/filesystems.md
WSL/index.md
WSL/install-manual.md
WSL/install-on-server.md
WSL/install.md
WSL/kernel-release-notes.md
WSL/networking.md
WSL/release-notes.md
WSL/setup/environment.md
WSL/store-release-notes.md
WSL/troubleshooting.md
WSL/tutorials/gpu-compute.md
WSL/tutorials/gui-apps.md
WSL/tutorials/wsl-containers.md
WSL/tutorials/wsl-database.md
WSL/tutorials/wsl-git.md
WSL/tutorials/wsl-vscode.md
WSL/vhd-size.md
WSL/wsl2-mount-disk.md

This is a bulk fix - According to the new DevRel GX group mission, the Localization production team drives the localization priority and translation quality per customer usage data, e.g. Page View or MAU of the language. The localization priority is defined by the project setting in localization pipeline - ms.localizationpriority in the source file is no longer used as a driving parameter to define the localization priority. https://review.docs.microsoft.com/help/contribute/localization-checklist-for-writer?branch=master#stop-using-mslocalizationpriority-metadata

Bulk fix - Removing .localizationpriority

---

WSL/install.md

My fix repairs the currently broken Markdown on https://docs.microsoft.com/en-us/windows/wsl/install:

fix: Broken Markdown in breadcrumb navigation

---

WSL/connect-usb.md

Based on https://github.com/dorssel/usbipd-win/wiki/WSL-support#usbip-client-tools there are simplified setup instructions in versions 2.0.0 of usbipd-win. This simplified setup is required for versions 2.0.0 and later, and compatible with earlier versions, so we should only document the simplified version in the docs article.

Update installation instructions for version 2.0.0

---

WSL/install-manual.md
WSL/install-on-server.md
WSL/install.md

Hi,
I noticed that many users (myself included...) launched a regular PowerShell to run `wsl --install` before realizing that it required more privileges because the message about the requirement of launching PowerShell **as administrator** wasn't visible enough.
So I'm proposing to put the information in bold.
Unrelated question : as a French user I'm accessing a French version of the documentation but can't see any i18n files in the repository. Is it done automatically?
Thank you

fix: Add bold around **as administrator** required privileges

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/docs-issue.md
ISSUE_TEMPLATE.md

This updates the issue template to the newer format and provides a issue chooser:

Update issue template

---

WSL/tutorials/wsl-git.md

This PR is the result of running a Link Repair script on the included content. This script is primarily being run to clean up links to function correctly in Air Gapped Clouds (AGC). Here's a breakdown of what the script that generated the changes in this PR fixes: 
- docs.microsoft.com Fully Qualified Domain Name (FQDN) Links to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not 
- azure.microsoft.com/documentation/articles that reflect to Docs to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not 
- All known flavors of MSDN/TechNet domains (we know of 8 or 9 now) that reflect to Docs to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not 
- This also includes cleanup of the appended query string for MSDN …

LinkFix: wsl (2022-03)

---

WSL/tutorials/gui-apps.md

Original Page states: https://www.intel.com/content/www/us/en/download/19344/30579/intel-graphics-windows-dch-drivers.html is version 30.0.100.9684
New page is version: 30.0.101.1191

Update Intel drivers link to latest version

---

WSL/tutorials/wsl-git.md

The path to git-credential-manager-core.exe has changed according to this [PR](https://github.com/git-for-windows/build-extra/pull/406) and the comments in the [v2.36.1 release notes](https://github.com/git-for-windows/git/releases/tag/v2.36.1.windows.1)

Update docs to reflect GCM new path and avoid errors

---

WSL/tutorials/gpu-compute.md

Some backslashes have been misplaced before the underscores in the bash commands.

Removing typos in bash commands

---

WSL/release-notes.md

Broken links related to "LTP Test Run Logs" are removed since no longer exist in GitHub repo.

[BrokenLinksH2] Fix path in link

---

WSL/tutorials/wsl-git.md

When (windows) git version is < 2.3.1 the executable name of the credential helper is `git-credential-manager.exe` instead of `git-credential-manager-core.exe`

docs: fix the credential helper path

---

WSL/wsl-config.md

From my understanding `kernel` and `swapfile` in `.wslconfig` should be of type `path` as they represent Windows paths and are also handled in the example like it is described for the value type `path`.

Fixed wslconfig value types

---

WSL/tutorials/linux.md

This PR is the result of running a Link Repair script on the included content. This script is primarily being run to clean up links to function correctly in Air Gapped Clouds (AGC). Here's a breakdown of what the script that generated the changes in this PR fixes: 
- docs.microsoft.com Fully Qualified Domain Name (FQDN) Links to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not 
- azure.microsoft.com/documentation/articles that reflect to Docs to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not 
- All known flavors of MSDN/TechNet domains (we know of 8 or 9 now) that reflect to Docs to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not 
- This also includes cleanup of the appended query string for MSDN …

LinkFix: WSL (2022-11)

---

WSL/tutorials/wsl-git.md

"Git Credential Manager Core" was renamed to "Git Credential Manager". See: https://aka.ms/gcm/rename
The newest version of Git for Windows (2.39.0) now complains if you use the old binary:
```
$ git push
warning: git-credential-manager-core was renamed to git-credential-manager
warning: see https://aka.ms/gcm/rename for more information
warning: git-credential-manager-core was renamed to git-credential-manager
warning: see https://aka.ms/gcm/rename for more information
Everything up-to-date
```

docs: fix the credential helper path again

---

WSL/enterprise.md
WSL/troubleshooting.md

There was a minor spelling error in the title of the "WSL has no network connection on my work machine or in an Enterpise environment" title. Fixed in this PR.

Fixed spelling error: Enterpise into Enterprise

---

WSL/compare-versions.md

WSL was initially introduced in 2016, while WSL 2 was introduced in 2019.
ref: https://www.howtogeek.com/248177/whats-new-in-windows-10s-anniversary-update/#:~:text=Windows%20Gets%20Its%20Own%20Linux%20Command%20Line

Fix Windows build number introducing WSL

---

WSL/tutorials/gpu-compute.md

The `apt-key add` method for storing signing authorities is deprecated, due to a vulnerability in which an illegitimate package could be signed by the wrong authority, and thus allowed to complete download despite being potentially malicious. See [here](https://wiki.debian.org/DebianRepository/UseThirdParty) for further reading.
This change updates to instead use the recommended keyrings approach, with the `[signed-by=` field to protect against the above exploit. This is the approach NVIDIA already recommends, for example [this installation guide](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html).

Don't instruct on using exploitable key storage

---

WSL/tutorials/gui-apps.md

Teams package from this tutorial is missing: https://teams.microsoft.com/downloads/desktopurl?env=production&plat=linux&arch=x64&download=true&linuxArchiveType=deb

docs: delete teams tutorial due to missing package

---

WSL/docfx.json

@craigloewen-msft could you please help to merge this metadata change (adobe-target=true) to main branch and then to live? This is to enable A/B testing ability across many url base paths so we can improve Learn user experience based on data-driven decisions. This meta (adobe-target) itself will not change how your content is displayed or modify any other UI behaviors so it is safe to merge.

add the adobe-target metadata for A/B testing

---

WSL/tutorials/gui-apps.md

- Fixes https://github.com/MicrosoftDocs/WSL/issues/1681.
- Use gnome-text-editor to replace gedit in the introduction of the document.

Use gnome-text-editor to replace gedit in the introduction of the document

---

WSL/basic-commands.md

Fix small typo: `instal` ➝ `install`

---

WSL/breadcrumb/toc.yml
WSL/docfx.json

This PR brings breadcrumb implementation into alignment with [platform architecture requirements](https://review.learn.microsoft.com/en-us/help/platform/navigation-overview?branch=main#requirements-for-content-ecosystems). This PR is part of a previously announced batch of breadcrumb fixes across the Learn platform and will be auto-merged if there are no build warnings. This PR may include removing the “extend breadcrumb” feature from any docfx files that are still using it, fixing breadcrumb file references in the docfx file, and rewriting breadcrumb files to match the [approved breadcrumb pattern](https://review.learn.microsoft.com/en-us/help/platform/navigation-breadcrumbs-overview?branch=main#breadcrumbs-in-documentation) for a given product’s documentation.

Fix breadcrumbs

---

WSL/systemd.md
WSL/toc.yml

If you have doubts how it is spelled, please see https://freedesktop.org/wiki/Software/systemd/ `Spelling` section

Fix systemd spelling

---

WSL/release-notes.md

This PR fixes the following suggestions  
> Link 'https://devblogs.microsoft.com/commandline/the-initial-preview-of-gui-app-support-is-now-available-for-the-windows-subsystem-for-linux' points to a page that doesn't exist. Check the path or URL and update the link.
This issue has been present for a long time, but since it was only a suggestion, it seems that no one has attempted to fix it. I've found an updated link and have made the corrections in the documentation.

fix broken link

---

WSL/wsl-config.md

I've updated the `useWindowsDnsCache` setting description to match its literal meaning: 
When set to true, it uses Windows DNS cache; when false, it bypasses it. 
The current documentation describes the opposite, which is counterintuitive. 
This might be an oversight, and this PR corrects it to prevent any confusion.

Update `useWindowsDnsCache` explanation to avoid confusion

---

WSL/tutorials/wsl-containers.md

Running Dev Containers: **Open Folder in Container...** when using this guide is not / no longer correct, as most readers will already have opened the folder while connected to WSL based on the steps provided above. We need to use **Dev Containers: Reopen in Container** or it will fail to create the .devcontainer folder and devcontainer.json and give a (unfortunately not very clear) error message.
See also: https://code.visualstudio.com/docs/devcontainers/containers#_open-a-wsl-2-folder-in-a-container-on-windows
- Use the Dev Containers: Reopen in Container command from a folder already opened using the WSL extension.
- Select Dev Containers: Open Folder in Container... from the Command Palette (F1) and choose a WSL folder using the local \\wsl$ share (from the Windows side).

Updated guide to fix an issue because of a wrong command

---

WSL/tutorials/gui-apps.md

I figured, if we are already referencing use of APT, and using it too, why use DPKG directly?
I simply changed the command to use APT to install google chrome, and its dependencies, rather than using 3 separate steps just for installing.

Update gui-apps.md to simplify commits.

---

WSL/faq.yml

FAQ: Split Hyper-V and Windows Home questions into two

---

WSL/basic-commands.md
WSL/faq.yml

- My original intent was to clarify that the export command exports a **snapshot** of the specified distribution. The way it is currently written doesn't say otherwise, but it could be interpreted to mean it exports a clean install without the user's modifications. 
- In other words, it could be saying `wsl --export Ubuntu ubuntu.tar` outputs the equivalent of downloading the official "ubuntu.tar" from the internet. 
- Splitting these two was not part of my original goal, merely a step along the way to achieve it.

Import export command clarification

---

WSL/troubleshooting.md

There are known incompatibilities when the Network Manager service is running within the Linux container. This documents this issue and how to stop that service.

Update troubleshooting.md when Network Manager is running

---

WSL/wsl-config.md

@benhillis stated in https://github.com/microsoft/WSL/issues/9636
> Based on previous feedback, this was modified to be 50% (without the 8GB upper limit). We will update the docs.
Let's make that happen :).

Fix memory default information in wsl-config.md

---

WSL/filesystems.md

Closes: https://github.com/MicrosoftDocs/WSL/issues/1707

Update filesystems.md to clarify Linux path

---

WSL/faq.yml

Update faq.yml to include note about setting username for moving distros

---

WSL/wsl-config.md

For example in Simplified Chinese documentation the value ”true“ is translated as ”是“ actually it should not be translated https://learn.microsoft.com/zh-cn/windows/wsl/wsl-config#main-wsl-settings

Prevent content from being translated in other language documents that should not be translated

---

WSL/basic-commands.md
WSL/enterprise.md
WSL/troubleshooting.md
WSL/wsl-config.md
WSL/wsl2-mount-disk.md

Representing customer feedback updates

Main > Live

---

WSL/disk-space.md

This PR addresses the issue where the first attempt to run wsl --shutdown using an unprivileged PowerShell fails.
1. Fill the VHD to its capacity and follow the instructions to fix the read-only fallback error.
1. In the *Read-only fallback error* section, use an unprivileged PowerShell to run `wsl.exe --shutdown`.
1. Observe the error as shown in the image below: 
Run the command in a privileged PowerShell session.

Update WSL shutdown instructions for clarity by specifying PowerShell should be run as administrator before executing the shutdown command.

---

WSL/build-custom-distro.md

This change adds documentation for the new `shortcut.enabled` and `windowsterminal.enabled`  configuration values in `wsl-distribution.conf`

Add documentation for shortcut.enabled and windowsterminal.enabled

---

WSL/networking.md

This pull request includes a small change to the `WSL/networking.md` file. The change improves the readability of the instructions for getting the IP address of the host machine by formatting the command as a code block.
* [`WSL/networking.md`](diffhunk://#diff-eda329c65c5e7b31eda1abcb1a3a6becf25128df66aefc8c7e161e8f19acd29fL67-R71): Formatted the command to get the IP address of the host machine as a code block for better readability.
Without this change, the command gets inline and breaks at the beginning, confusing the reader, making them think the command begins by route instead of ip.

Put the whole command in a block

---

WSL/systemd.md

> Notice: If your Linux distribution is Debian/Ubuntu/Kali Rolling, you should not only have installed the systemd package, but also make sure the systemd-sysv package is installed.
```bash
sudo apt-get update -y && sudo apt-get install systemd systemd-sysv -y
```

make sure the systemd-sysv package is installed

---

WSL/disk-space.md

This adds a section that utilizes the `wsl --manage` command to resize a hard drive instead of the currently present manual steps.

Update resizing docs for new manage command

---

WSL/wsl-config.md

This pull request includes updates to the `WSL/wsl-config.md` file to support specifying custom Linux kernel modules for WSL 2. The key changes are:
* Added a new configuration option `kernelModules` to specify the path to a custom Linux kernel modules VHD in the configuration table.
* Added an example usage of the `kernelModules` option in the configuration file.

add kernelModules documentation

---

WSL/wsl-config.md

This pull request includes a minor update to the `WSL/wsl-config.md` file. The change updates the default value for the `kernelModules` option to reflect the Microsoft built kernel modules provided inbox.
Documentation update:
* [`WSL/wsl-config.md`](diffhunk://#diff-541b84f25ec8814d5a284202d3676efd58b732f46079dffb2dbd02dd7d4f492dL209-R209): Updated the default value for the `kernelModules` option to "The Microsoft built kernel modules provided inbox" instead of "An absolute Windows path to a custom Linux kernel modules VHD."

Add the default column value for kernelModules

---

WSL/networking.md

The lower case "-i" will return a "127.0.1.1" which is a loop back address. The address cannot be accessed from Windows side. The upper-case "-I" instead will return the outside address of the WSL instance seen by Windows.
Thus "-I" should be used instead of "-i" to get the host IP seen from WSL. There's already a note saying about this below the changed part.
This commit mainly reverts the change of PR #2033.

Fix incorrect "hostname -i" command in networking.md

---

WSL/install-manual.md
WSL/install-on-server.md

Based on some experiences I had setting up WSL on server core, both with Azure VMs and Hyper-V on my laptop.
https://serverfault.com/questions/1169719/wsl-distributions-do-not-install-on-windows-server-core-2025/1169879#1169879

Updated docs for server core.

---

WSL/wsl-config.md

Fixes #1628 and fixes #1767 so that the docs are consistent with the real behavior of WSL2. From testing, WSL has a default umask of 000, not 022.
1. Create a new file: `touch /mnt/c/temp/testfile`.
2. Edit /etc/wsl.conf so that the `[automount]` section does not contain the key-value pair `options = ...` and save the file. This ensures the default umask is applied.
3. Run `wsl.exe --shutdown`.
4. Wait 8 seconds.
5. Open WSL and check the mode of the test file:
```sh
$ ls -lh /mnt/c/temp/testfile
-rwxrwxrwx 1 myusername myusername 0 Dec  0 09:33 /mnt/c/temp/testfile
```
Note that all the permission bits are set, meaning the default umask is `000`: anyone can read, write, or execute files.

Fix umask default for DrvFs automount

---

WSL/troubleshooting.md

There are compatibility issues with the Microsoft Global Secure Access Client and WSL. Updating troubleshooting to help unblock WSL users.

Update troubleshooting.md with troubleshooting tips with GSA

---

WSL/basic-commands.md

This pull request includes a small change to the `WSL/basic-commands.md` file. The change updates the section header to better reflect the command's functionality. 
* [`WSL/basic-commands.md`](diffhunk://#diff-b05a62aae85143e23a31dcfb224c091ec5749ab6b0a594fda9f4104f3f140041L78-R78): Changed the section header from "Change directory to home" to "Start WSL in user's home."

"Change directory to home" is not accurate

---

WSL/wsl-config.md

Use consistent capitalization and spacing for tables, use `""` as the default for blank strings, use a proper `size` value as a default for `defaultVhdSize`, and add some missing code tags.

Use consistent table formatting in wsl-config

---

WSL/wsl-config.md

Added docs for some existing wsl.conf options

Documented new wsl.conf options

---

WSL/install-on-server.md

Due to a misplaced dollar sign, variable reference was not valid.

Fix variable reference

---

WSL/connect-usb.md

Update the connect-usb.md doc to reflect that ARM64 is now supported by USBIPD since v5.0.0.
I had success using this on an ARM64 laptop with Windows 11.
Closes: https://github.com/MicrosoftDocs/WSL/issues/2032

connect-usb: ARM64 is now supported

---

WSL/tutorials/wsl-database.md

This PR fixes the broken link to the PostgreSQL extension in the WSL database tutorial.
The original link (`ms-ossdata.vscode-postgresql`) returned a 404 error.  
Updated it to the correct extension: `ms-ossdata.vscode-pgsql`.
Fixes #2310

Fix broken PostgreSQL extension link in WSL database tutorial (#2310)
